---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-operator
  namespace: kube-system
spec:
  chart:
    spec:
      chart: postgres-operator
      sourceRef:
        kind: HelmRepository
        name: zalando-postgres-operator
        namespace: flux-system
  interval: 30m
  releaseName: postgres-operator
  valuesFrom:
  - kind: ConfigMap
    name: postgres-operator-values
