apiVersion: v1
kind: Pod
metadata:
  name: admin-shell
  namespace: playkube
spec:
  containers:
  - command:
    - bash
    - -c
    - |-
      wget -O /tmp/kubeadm https://storage.googleapis.com/kubernetes-release/release/v1.21.8/bin/linux/amd64/kubeadm && chmod +x /tmp/kubeadm
      sleep infinity
    env:
    - name: KUBECONFIG
      value: /etc/kubernetes/admin.conf
    image: bitnami/kubectl:1.21.8
    name: kubectl
    volumeMounts:
    - mountPath: /etc/kubernetes
      name: admin-kubeconfig
    - mountPath: /opt/kubeadm
      name: kubeadm-config
  restartPolicy: Always
  volumes:
  - name: admin-kubeconfig
    secret:
      secretName: admin-kubeconfig
  - name: kubeadm-config
    configMap:
      name: kubeadm-config
