apiVersion: apiserver.k8s.io/v1beta1
kind: EgressSelectorConfiguration
egressSelections:
- name: cluster
  connection:
    proxyProtocol: HTTPConnect
    transport:
      tcp:
        url: https://konnectivity-server:8090
        tlsConfig:
          caBundle: /opt/certs/apiserver-konnectivity/ca.crt
          clientKey: /opt/certs/apiserver-konnectivity/tls.key
          clientCert: /opt/certs/apiserver-konnectivity/tls.crt
