apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: front-proxy-ca
  namespace: playkube
spec:
  isCA: true
  commonName: front-proxy-ca
  secretName: front-proxy-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: front-proxy-ca-issuer
  namespace: playkube
spec:
  ca:
    secretName: front-proxy-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: front-proxy-client
  namespace: playkube
spec:
  secretName: front-proxy-client-cert
  privateKey:
    algorithm: ECDSA
    size: 256
  usages: [client auth]
  commonName: front-proxy-client
  issuerRef:
    name: front-proxy-ca-issuer
    kind: Issuer
    group: cert-manager.io
