apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: playkube
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubernetes-ca
  namespace: playkube
spec:
  isCA: true
  commonName: kubernetes-ca
  secretName: kubernetes-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: kubernetes-ca-issuer
  namespace: playkube
spec:
  ca:
    secretName: kubernetes-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apiserver-etcd
  namespace: etcd
spec:
  secretName: apiserver-etcd
  secretTemplate:
    annotations:
      kubed.appscode.com/sync: "playcluster="
  privateKey:
    algorithm: ECDSA
    size: 256
  usages: [client auth]
  commonName: playkube
  issuerRef:
    name: etcd-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: admin
  namespace: playkube
spec:
  secretName: admin-cert
  privateKey:
    algorithm: ECDSA
    size: 256
  usages: [client auth]
  commonName: cluster-admin
  subject:
    organizations: [system:masters]
  issuerRef:
    name: kubernetes-ca-issuer
    kind: Issuer
    group: cert-manager.io
