apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: scheduler
  namespace: playkube
spec:
  secretName: scheduler-cert
  privateKey:
    algorithm: ECDSA
    size: 256
  usages: [client auth]
  commonName: system:kube-scheduler
  issuerRef:
    name: kubernetes-ca-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scheduler
  name: scheduler
  namespace: playkube
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
      - image: k8s.gcr.io/kube-scheduler:v1.21.8
        name: kube-scheduler
        command:
        - kube-scheduler
        - --authentication-kubeconfig=/opt/kubeconfig/kubeconfig
        - --authorization-kubeconfig=/opt/kubeconfig/kubeconfig
        - --kubeconfig=/opt/kubeconfig/kubeconfig
        - --port=0
        volumeMounts:
        - mountPath: /opt/cert
          name: cert
        - mountPath: /opt/kubeconfig
          name: kubeconfig-template
      volumes:
      - name: cert
        secret:
          secretName: scheduler-cert
      - name: kubeconfig-template
        configMap:
          name: kubeconfig-template
