apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate
  namespace: synapse
spec:
  secretName: certificate
  dnsNames:
    - matrix.samcday.com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
