apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: synapse
  name: synapse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synapse
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: synapse
    spec:
      containers:
      - image: matrixdotorg/synapse
        name: synapse
        ports:
        - containerPort: 8008
        env:
        - name: SYNAPSE_CONFIG_PATH
          value: /config/homeserver.yaml
        volumeMounts:
        - name: config
          mountPath: /config
        - name: signing-key
          mountPath: /signing-key
        - name: media
          mountPath: /media
      initContainers:
      - name: config
        image: alpine:3.15.0
        command:
        - sh
        - -c
        - |-
          apk add gettext
          cp /config-template/log.yaml /config/log.yaml
          envsubst < /config-template/homeserver.yaml > /config/homeserver.yaml
        env:
        - name: PGPASS
          valueFrom:
            secretKeyRef:
              name: synapse-user.synapse-db.credentials.postgresql.acid.zalan.do
              key: password
        - name: MACROON_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: synapse
              key: MACROON_SECRET_KEY
        volumeMounts:
        - name: config-template
          mountPath: /config-template
        - name: config
          mountPath: /config
      volumes:
      - name: config-template
        configMap:
          name: homeserver
      - name: config
        emptyDir: {}
      - name: signing-key
        secret:
          secretName: signing-key
      - name: media
        persistentVolumeClaim:
          claimName: media
