---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-exporter
  namespace: synapse
spec:
  chart:
    spec:
      chart: prometheus-postgres-exporter
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: 2.4.0
  interval: 1h
  releaseName: postgres-exporter
  values:
    config:
      datasource:
        host: synapse-db
        passwordSecret:
          name: postgres.synapse-db.credentials.postgresql.acid.zalan.do
          key: password
        sslmode: require
    serviceMonitor:
      enabled: true
