apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: synapse-db
spec:
  teamId: synapse
  volume:
    size: 10Gi
  numberOfInstances: 2
  users:
    synapse_user: []
  databases:
    synapse: synapse_user
  postgresql:
    version: "13"
  patroni:
    initdb:
      encoding: UTF8
      locale: C
  enableLogicalBackup: false
