apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: secrets
spec:
    secretTemplates:
        - name: postgres-pod-secrets
          stringData:
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:tHSzXH0u2LI2Mz3x7aTv4LxrR8YZB0awDg==,iv:Mxbcer20nK1NTmsWapJZWcoV3VZraq+UrBsv/NQ29vU=,tag:wfgZHGsgRZqSG6/YcW5sBg==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:CHHx7UkY+R2SgrCBOmSIacASsmoRc8kdTgt4BtmzKw==,iv:kJP9WsRNv4tO79Sqz7ukPuP7aYvoARyvg0dvmqli+yM=,tag:fpFMEL4xley7SlhvfFwh7w==,type:str]
            AWS_ENDPOINT: ENC[AES256_GCM,data:pvW7G/m5FbhGtb7x3XHPIaZZrYokPX0PPRZXcVCHZJKk57Ag0DU6ZZW3wptP,iv:hTB3mVt0GjLhClFtbPleDcM4GQyQsiQVVbXPwIab10E=,tag:bU8tpa/A/WFmACnkCNG7yg==,type:str]
            WALE_S3_ENDPOINT: ENC[AES256_GCM,data:/ghuJ3fSfCwqYvHbCe2kjjornP4BwhpqChQBCih1muxtbq0n6RJtYxaZdARcLuq3bOI=,iv:KwUIwJJjY1d6xdT1jYu7PmV+WDxiqTHleSACKZOZQx4=,tag:dz31Z5ISih6abbQwvLxW6A==,type:str]
            CLONE_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ZJjCagGnRIXNtAEcjIiNy1zKbuCu/yVpkw==,iv:tTigM/eQTLr9oXcgTJRXv9+t4l34wdoq1TwvRosuEfc=,tag:g69fxmWU5ENk7mcn7ROi7g==,type:str]
            CLONE_AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:nZ92g6ztpZKCG1dPQ5XcU8Du0E0n2mlE/JKLbpuEAg==,iv:lPWNLLdXpB0CFtRUWjWHX6ZFqFy8VJ5CVJ1c0167kmw=,tag:0u4EnL6mtHslAmbW/Jkn/g==,type:str]
            CLONE_AWS_ENDPOINT: ENC[AES256_GCM,data:dHLTFOEk1wBFEcf9OkOckBdWbDXiGhinEX5AQAvnbjJcN6607GlitKNuql6x,iv:C7VptHlUzyx4jJMlxsGABziw2XlatLLkrsphzQHge2Q=,tag:q+kpL2ugr/mMZUu1L0woKg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kztlwk25hdsy8s2gqlkx4aucdwss5zfaejadtnv5s2zd7vmslq0s8gqltu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQ09za1Joc29uY2N5S0JG
            L0RMQVJ2ZjFIeXlncDJMZkZZanZ1c0s5UFVVClF6b1pzQ1BLK2E4QXlMMG1QNXRC
            bmFxL2k3Zm5Wd1F3WmhKb3Q3YnU0L1UKLS0tIFNSa1VGY0lEN0hmWkZSd1BWUmM2
            VERGWm9sK3pwUjNoWXBwZnFxQUQxL00Kkie1Lupsd3bR7sw856aV/Ro3FAPH/Nn2
            ULK8FUa1xAdF/eMsDxb/OVw3m3AjIVscB/7hDYEAlv4K7etoth6xvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-31T11:17:27Z"
    mac: ENC[AES256_GCM,data:bfgbxoGziBSXmoXw0tvUtR8L3+Ax3NrPBxpb5nYsE9xplGtlGL6NYoTQXKzxSz+gGaTr16RXIsBPL3qDNYHgVqYVL6GGcgnTMm8vj6LidNWwt8x8xuAOH0t3D5ZRVv11Vgk/nqVZnWqDnZBtpDjKNLHR9YbGAnmB2K34GoNvlOk=,iv:8QeBtCseVVzCB/Zvrz0x0MR0oOzGZR6LzuZioAcMHqE=,tag:ghQS/pe8e2h/2j/zYO3Wzg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
