apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: synapse-db
  namespace: synapse
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: synapse-db
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
    - containerName: "*"
      controlledValues: RequestsOnly
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: synapse
  namespace: synapse
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: synapse
  updatePolicy:
    updateMode: Initial
  resourcePolicy:
    containerPolicies:
    - containerName: "*"
      controlledValues: RequestsOnly
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: mautrix-signal
  namespace: synapse
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mautrix-signal
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
    - containerName: "*"
      controlledValues: RequestsOnly
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: mautrix-telegram
  namespace: synapse
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mautrix-telegram
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
    - containerName: "*"
      controlledValues: RequestsOnly
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: mautrix-whatsapp
  namespace: synapse
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mautrix-whatsapp
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
    - containerName: "*"
      controlledValues: RequestsOnly
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: postgres-exporter
  namespace: synapse
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: synapse-postgres-exporter-prometheus-postgres-exporter
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
    - containerName: "*"
      controlledValues: RequestsOnly
