apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: secrets
spec:
    secretTemplates:
        - name: cloudflare
          stringData:
            token: ENC[AES256_GCM,data:3WyMwK4d6i3w3+If39bbi/a7H0ovdWg9/U9QEtWAeprlC33GUxJrmA==,iv:DeNecVCtc4cHet3f8bjoKl7Odsi+KIvUrwJLMWH1H+I=,tag:U8qS6PoXnq5bUChgH+HMyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kztlwk25hdsy8s2gqlkx4aucdwss5zfaejadtnv5s2zd7vmslq0s8gqltu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNnNwdnNLZFRydlV3VjJF
            aGorU3pscUlFMW1LNS9Rb1lzTDJQa0JlNG1VCkMzRXZrQXJKRE9maXNUOHNTVG9w
            bzJlbk5UbUZ1bDUwY0RZM0s1WVJRZ0kKLS0tIFB1QkxObjBpMUlzTlFwNUd4MVhI
            eC9SczJwelVnc1k0MGdiTDlRaldyTGMKflmB7HJ46Csvqm1hlMIhAvXedfuKf3Vk
            WBHIXLwYZlnh4nPFnO9OLdnu7da6ES3YWP7o6sRwcWbsMMue3lQ4vA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-31T18:35:44Z"
    mac: ENC[AES256_GCM,data:O8oqwy5cgrIEXNrx1mfbm7Ea9ZdnUjdor5Wq7KAfe8agREgIn2Rkk6B+nYI3tbXtNSqwt1fSF83lSA2jgKXbESwUd7k3BPo/qv6MGn79EXa/AmsJKiFixkl51UdTWv8fEglsvJbO71eByT9CEJUbyxO4LI4MvrajtD/ckEZHKQw=,iv:1XgDyEWffQv86GbKowiXNB9wEJZyyvrUV7z+OB+mGVw=,tag:LTZuavswvsvCInZnbUzGrg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
