---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      version: 4.0.17
  interval: 30m
  releaseName: ingress-nginx
  targetNamespace: kube-system
  valuesFrom:
  - kind: ConfigMap
    name: ingress-nginx-values
