# https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml

controller:
  kind: Deployment
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 85
    targetMemoryUtilizationPercentage: ~
  tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
  service:
    externalIPs: [78.46.240.242]
