controller:
  kind: Deployment
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 85
    targetMemoryUtilizationPercentage: ~
  config:
    use-proxy-protocol: true
  extraArgs:
    enable-ssl-passthrough: ""
  tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
  service:
    type: ClusterIP
    externalIPs: [78.46.240.242]
