apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apiserver
  namespace: play-cluster
spec:
  secretName: apiserver-cert
  privateKey:
    algorithm: ECDSA
    size: 256
  usages: [server auth]
  dnsNames:
  - apiserver.play-cluster.svc.cluster.local
  - apiserver
  - apiserver.play-cluster.samcday.com
  ipAddresses:
  - 49.12.17.240
  - 10.0.0.1
  issuerRef:
    name: kubernetes-ca-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apiserver
  name: apiserver
  namespace: play-cluster
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apiserver
  template:
    metadata:
      labels:
        app: apiserver
    spec:
      containers:
      - image: k8s.gcr.io/kube-apiserver:v1.21.8
        name: kube-apiserver
        command:
        - kube-apiserver
        - --advertise-address=49.12.17.240
        - --allow-privileged
        - --authorization-mode=Node,RBAC
        - --client-ca-file=/opt/certs/apiserver/ca.crt
        - --egress-selector-config-file=/opt/esc/egress-selector-config.yaml
        - --enable-bootstrap-token-auth
        - --etcd-cafile=/opt/certs/etcd-client/ca.crt
        - --etcd-certfile=/opt/certs/etcd-client/tls.crt
        - --etcd-compaction-interval=0
        - --etcd-keyfile=/opt/certs/etcd-client/tls.key
        - --etcd-prefix=/play-cluster
        - --etcd-servers=https://etcd.etcd.svc.cluster.local:2379
        - --proxy-client-cert-file=/opt/certs/front-proxy-client/tls.crt
        - --proxy-client-key-file=/opt/certs/front-proxy-client/tls.key
        - --requestheader-allowed-names=front-proxy-client
        - --requestheader-client-ca-file=/opt/certs/front-proxy-client/ca.crt
        - --secure-port=6444
        - --service-account-issuer=https://apiserver.play-cluster.svc.cluster.local
        - --service-account-key-file=/opt/sa/pub
        - --service-account-signing-key-file=/opt/sa/key
        - --tls-cert-file=/opt/certs/apiserver/tls.crt
        - --tls-private-key-file=/opt/certs/apiserver/tls.key
        volumeMounts:
        - mountPath: /opt/certs/apiserver
          name: apiserver-cert
        - mountPath: /opt/certs/apiserver-konnectivity
          name: apiserver-konnectivity-cert
        - mountPath: /opt/esc
          name: egress-selector-config
        - mountPath: /opt/certs/etcd-client
          name: etcd-client-cert
        - mountPath: /opt/certs/front-proxy-client
          name: front-proxy-client-cert
        - mountPath: opt/sa
          name: sa
      volumes:
      - name: apiserver-cert
        secret:
          secretName: apiserver-cert
      - name: apiserver-konnectivity-cert
        secret:
          secretName: apiserver-konnectivity-cert
      - name: egress-selector-config
        configMap:
          name: egress-selector-config
      - name: etcd-client-cert
        secret:
          secretName: apiserver-etcd
      - name: front-proxy-client-cert
        secret:
          secretName: front-proxy-client-cert
      - name: sa
        secret:
          secretName: sa
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: apiserver
  name: apiserver
  namespace: play-cluster
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
    external-dns.alpha.kubernetes.io/hostname: apiserver.play-cluster.samcday.com
spec:
  type: NodePort
  externalIPs: [49.12.17.240]
  ports:
  - port: 6444
    protocol: TCP
    targetPort: 6444
    nodePort: 30644
  selector:
    app: apiserver
