apiVersion: batch/v1
kind: Job
metadata:
  name: generate-admin-kubeconfig
  namespace: play-cluster
spec:
  template:
    spec:
      containers:
      - name: kubectl
        command:
        - /bin/bash
        - -c
        - |-
          set -uexo pipefail
          if kubectl describe secret/admin-kubeconfig; then exit; fi
          KUBECONFIG=/opt/kubeconfig/kubeconfig kubectl config view --flatten > /tmp/admin.conf
          kubectl create secret generic admin-kubeconfig --from-file=/tmp/admin.conf
        image: bitnami/kubectl:1.21.8
        volumeMounts:
        - mountPath: /opt/kubeconfig
          name: kubeconfig-template
        - mountPath: /opt/cert
          name: cert
      serviceAccountName: generate-admin-kubeconfig
      restartPolicy: OnFailure
      volumes:
      - name: cert
        secret:
          secretName: admin-cert
      - name: kubeconfig-template
        configMap:
          name: kubeconfig-template
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: generate-admin-kubeconfig
  namespace: play-cluster
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: generate-admin-kubeconfig
  namespace: play-cluster
rules:
- apiGroups: [""]
  resources: [secrets]
  resourceNames: [admin-kubeconfig]
  verbs: [get]
- apiGroups: [""]
  resources: [secrets]
  verbs: [create]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: generate-admin-kubeconfig
  namespace: play-cluster
subjects:
- kind: ServiceAccount
  name: generate-admin-kubeconfig
roleRef:
  kind: Role
  name: generate-admin-kubeconfig
  apiGroup: rbac.authorization.k8s.io
