---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: libreddit
  namespace: libreddit
spec:
  chart:
    spec:
      chart: generic
      sourceRef:
        kind: HelmRepository
        name: morremeyer
        namespace: flux-system
      version: 3.0.4
  interval: 1h
  releaseName: libreddit
  valuesFrom:
  - kind: ConfigMap
    name: libreddit-values
