apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: libreddit
configMapGenerator:
- name: libreddit-values
  files: [values.yaml]
resources:
- ../kustomizeconfig
- helm-release.yaml
- limit-range.yaml
- namespace.yaml
- secrets.yaml
- vpa.yaml
