apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: libreddit
  namespace: libreddit
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: libreddit-generic
  updatePolicy:
    updateMode: Auto
