apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
apiServer:
  extraArgs:
    authorization-mode: Node,RBAC
  timeoutForControlPlane: 4m0s
certificatesDir: /etc/kubernetes/pki
clusterName: personal
controlPlaneEndpoint: ${loadbalancer_ip}:6443
controllerManager:
  extraArgs:
    bind-address: 0.0.0.0
dns:
  type: CoreDNS
etcd:
  local:
    dataDir: /var/lib/etcd
    extraArgs:
      listen-metrics-urls: http://0.0.0.0:2381
imageRepository: k8s.gcr.io
kubernetesVersion: ${kube_version}
networking:
  dnsDomain: cluster.local
  podSubnet: 10.98.0.0/15
  serviceSubnet: 10.97.0.0/16
scheduler:
  extraArgs:
    bind-address: 0.0.0.0
