apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - https://github.com/kubernetes-sigs/metrics-server/manifests/release?ref=v0.5.2

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: metrics-server
    patch: |-
      - op: add
        path: /spec/template/spec/tolerations
        value:
          - key: node-role.kubernetes.io/master
            operator: Exists
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --kubelet-insecure-tls
