---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: monitoring
  targetNamespace: monitoring
  timeout: 1m
  values:
    kubeControllerManager:
      service:
        port: 10257
        targetPort: 10257
      serviceMonitor:
        https: true
        insecureSkipVerify: true
    kubeEtcd:
      service:
        port: 2381
        targetPort: 2381
    kubeScheduler:
      service:
        port: 10259
        targetPort: 10259
      serviceMonitor:
        https: true
        insecureSkipVerify: true
    kube-state-metrics:
      prometheus:
        monitor:
          additionalLabels:
            release: monitoring
