kubeControllerManager:
  service:
    port: 10257
    targetPort: 10257
  serviceMonitor:
    https: true
    insecureSkipVerify: true
kubeEtcd:
  service:
    port: 2381
    targetPort: 2381
kubeScheduler:
  service:
    port: 10259
    targetPort: 10259
  serviceMonitor:
    https: true
    insecureSkipVerify: true
prometheus:
  prometheusSpec:
    podMonitorSelectorNilUsesHelmValues: false
    resources:
      limits:
        cpu: 500m
        memory: 1536Mi
      requests:
        cpu: 500m
        memory: 1536Mi
    retention: 30d
    retentionSize: 30GB
    serviceMonitorSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: hcloud-volumes
          accessModes: [ReadWriteOnce]
          resources:
            requests:
              storage: 50Gi
    walCompression: true
