kubeControllerManager:
  serviceMonitor:
    insecureSkipVerify: true
kubeEtcd:
  service:
    port: 2381
    targetPort: 2381
kubeProxy:
  enabled: false
kubeScheduler:
  serviceMonitor:
    insecureSkipVerify: true
prometheus:
  prometheusSpec:
    podMonitorSelectorNilUsesHelmValues: false
    resources:
      limits:
        cpu: "1"
        memory: 1536Mi
      requests:
        cpu: 500m
        memory: 1536Mi
    retention: 30d
    retentionSize: 30GB
    serviceMonitorSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: hcloud-volumes
          accessModes: [ReadWriteOnce]
          resources:
            requests:
              storage: 50Gi
    walCompression: true

alertmanager:
  config:
    route:
      routes:
      - matchers:
        - alertname = Watchdog
        receiver: deadmanssnitch
        group_wait: 0s
        repeat_interval: 30m
      - matchers:
        - alertname != Watchdog
        receiver: pagerduty
    receivers:
    - name: deadmanssnitch
      webhook_configs:
      - url: "" # Set in secrets
    - name: pagerduty
      pagerduty_configs:
      - service_key: "" # Set in secrets
    - name: "null"
