apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/samcday/etcd-kube/
- root-shell.yaml
- root-user.yaml
patches:
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: etcd
    namespace: etcd
  patch: |-
    - op: replace
      path: /spec/template/spec/tolerations
      value: [{key: node-role.kubernetes.io/master, operator: Exists}]
    - op: replace
      path: /spec/template/spec/affinity
      value:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values: [etcd]
            topologyKey: "kubernetes.io/hostname"
    - op: add
      path: /spec/template/spec/containers/0/command/-
      value: --client-cert-auth=true
