---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://kubernetes.github.io/ingress-nginx

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  targetNamespace: ingress-nginx
  timeout: 1m
  install:
    createNamespace: true
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      version: 4.0.13
  interval: 1m0s
  releaseName: ingress-nginx
  values:
    controller:
      kind: DaemonSet
      config:
        use-proxy-protocol: true
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
      service:
        type: NodePort
        nodePorts:
          http: 32080
          https: 32443
        externalIPs: [49.12.17.240] # Could be nice to pull this dynamically from a CM set by bootstrap.sh, or something. 
        externalTrafficPolicy: Local
