---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: rook-ceph-operator
  namespace: rook-ceph
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rook-ceph-operator
  updatePolicy:
    updateMode: Initial
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: rook-ceph-mgr-a
  namespace: rook-ceph
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rook-ceph-mgr-a
  updatePolicy:
    updateMode: Initial
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: rook-ceph-mon-a
  namespace: rook-ceph
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rook-ceph-mon-a
  updatePolicy:
    updateMode: Initial
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: rook-ceph-osd-0
  namespace: rook-ceph
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rook-ceph-osd-0
  updatePolicy:
    updateMode: Initial
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: rook-ceph-osd-1
  namespace: rook-ceph
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rook-ceph-osd-1
  updatePolicy:
    updateMode: Initial
