---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-config-syncer
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kubed
      sourceRef:
        kind: HelmRepository
        name: appscode
      version: v0.13.0
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: kube-config-syncer
  targetNamespace: kube-config-syncer
