---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager-issuers
  namespace: kube-system
spec:
  interval: 15m0s
  path: ./kube-system/cert-manager/issuers
  prune: true
  sourceRef:
    kind: GitRepository
    name: personal-infrastructure
    namespace: flux-system
  timeout: 2m0s
  wait: true
