apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: flux-values
  namespace: flux-system
  files: [values.yaml]
resources:
- ../kustomizeconfig/
- gitrepos/personal-infrastructure.yaml
- helm-release.yaml
- helmrepos/bitnami.yaml
- helmrepos/cilium.yaml
- helmrepos/cowboysysop.yaml
- helmrepos/fluxcd-community.yaml
- helmrepos/grafana.yaml
- helmrepos/hcloud-fip-k8s.yaml
- helmrepos/ingress-nginx.yaml
- helmrepos/jetstack.yaml
- helmrepos/kubernetes-dashboard.yaml
- helmrepos/metrics-server.yaml
- helmrepos/morremeyer.yaml
- helmrepos/openebs.yaml
- helmrepos/prometheus-community.yaml
- helmrepos/sops-secrets-operator.yaml
- helmrepos/zalando-postgres-operator.yaml
- kustomizations/flux-system.yaml
- kustomizations/flux-system-extra.yaml
- kustomizations/invidious.yaml
- kustomizations/kube-system.yaml
- kustomizations/monitoring.yaml
- kustomizations/miniflux.yaml
- kustomizations/playkube.yaml
- kustomizations/synapse.yaml
- limit-range.yaml
- receiver.yaml
- webhook-ingress.yaml
