apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
- ../kustomizeconfig.yaml
configMapGenerator:
- name: flux-values
  namespace: flux-system
  files: [values.yaml]
resources:
- gitrepos/personal-infrastructure.yaml
- helm-release.yaml
- helmrepos/cilium.yaml
- helmrepos/cowboysysop.yaml
- helmrepos/fluxcd-community.yaml
- helmrepos/grafana.yaml
- helmrepos/ingress-nginx.yaml
- helmrepos/jetstack.yaml
- helmrepos/kubernetes-dashboard.yaml
- helmrepos/metrics-server.yaml
- helmrepos/openebs.yaml
- helmrepos/postgres-operator.yaml
- helmrepos/prometheus-community.yaml
- helmrepos/sops-secrets-operator.yaml
- kustomizations/cert-manager.yaml
- kustomizations/flux-system.yaml
- kustomizations/kube-system.yaml
- kustomizations/monitoring.yaml
- kustomizations/openebs.yaml
- limit-range.yaml
- receiver.yaml
- webhook-ingress.yaml