apiVersion: v1
kind: LimitRange
metadata:
  name: happy-cluster
  namespace: flux-system
spec:
  limits:
  - default:
      cpu: 1000m
      memory: 256Mi
    defaultRequest:
      cpu: 10m
      memory: 32Mi
    max:
      cpu: 1000m
      memory: 1Gi
    maxLimitRequestRatio:
      memory: 5
    min:
      cpu: 1m
      memory: 16Mi
    type: Container
