cli:
  tolerations: &tolerations
  - key: node-role.kubernetes.io/master
    operator: Exists
helmcontroller:
  replicas: 2
  tolerations: *tolerations
imageautomationcontroller:
  create: false
imagereflectorcontroller:
  create: false
kustomizecontroller:
  replicas: 2
  tolerations: *tolerations
notificationcontroller:
  tolerations: *tolerations
sourcecontroller:
  tolerations: *tolerations
