cli:
  tolerations: &tolerations
  - key: node-role.kubernetes.io/master
    effect: NoSchedule
    operator: Exists
helmcontroller:
  resources:
    requests:
      cpu: 50m
  tolerations: *tolerations
imageautomationcontroller:
  resources:
    requests:
      cpu: 10m
  tolerations: *tolerations
imagereflectorcontroller:
  resources:
    requests:
      cpu: 10m
  tolerations: *tolerations
kustomizecontroller:
  resources:
    requests:
      cpu: 50m
  tolerations: *tolerations
notificationcontroller:
  resources:
    requests:
      cpu: 50m
  tolerations: *tolerations
sourcecontroller:
  resources:
    requests:
      cpu: 50m
  tolerations: *tolerations
