cli:
  tolerations: &tolerations
  - key: node-role.kubernetes.io/master
    operator: Exists
helmcontroller:
  container:
    additionalargs: [--enable-leader-election]
  replicas: 2
  tolerations: *tolerations
imageautomationcontroller:
  create: false
imagereflectorcontroller:
  create: false
kustomizecontroller:
  tolerations: *tolerations
notificationcontroller:
  tolerations: *tolerations
sourcecontroller:
  tolerations: *tolerations
