---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  chart:
    spec:
      chart: promtail
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: 3.11.0
  interval: 1h
  releaseName: promtail
  valuesFrom:
  - kind: ConfigMap
    name: promtail-values
