---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: flux-system
spec:
  chart:
    spec:
      chart: openebs
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
      version: 3.1.0
  interval: 30m
  releaseName: openebs
  targetNamespace: kube-system
  valuesFrom:
  - kind: ConfigMap
    name: openebs-values
