---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: 2.16.0
  interval: 1h
  releaseName: loki
  valuesFrom:
  - kind: ConfigMap
    name: loki-values
