apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: loki-values
  namespace: flux-system
  files: [values.yaml]
resources:
- helm-release.yaml
- datasource.yaml
