---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: nitter
spec:
  chart:
    spec:
      chart: redis
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 16.8.4
  interval: 1h
  releaseName: redis
  valuesFrom:
  - kind: ConfigMap
    name: redis-values
