args:
- --kubelet-insecure-tls
# Might as well put metrics-server metrics in Prometheus!
metrics:
  enabled: true
podDisruptionBudget:
  enabled: true
  minAvailable: 1
replicas: 2
serviceMonitor:
  enabled: true
tolerations:
- key: node-role.kubernetes.io/control-plane
  operator: Exists
- key: node-role.kubernetes.io/master
  operator: Exists
nodeSelector:
  node-role.kubernetes.io/control-plane: ""
