apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: miniflux
configMapGenerator:
- name: miniflux-values
  files: [values.yaml]
resources:
- ../kustomizeconfig
- helm-release.yaml
- limit-range.yaml
- namespace.yaml
- postgres.yaml
- vpa.yaml