apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: miniflux-db
  namespace: miniflux
spec:
  teamId: miniflux
  volume:
    size: 10Gi
    storageClass: openebs-hostpath
  numberOfInstances: 2
  users:
    miniflux: []
  databases:
    miniflux: miniflux
  postgresql:
    version: "13"
  patroni:
    initdb:
      encoding: UTF8
      locale: C
  enableLogicalBackup: false
