apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: secrets
    namespace: miniflux
spec:
    secretTemplates:
        - name: postgres-pod-secrets
          stringData:
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:aUdj0Agf+DY3zR1J9LccE4OupHW4WK9NLA==,iv:Nk1ebvtz0suzA76/WfnvHjXYOn+q7aAGWrNOQXcZpGY=,tag:CLxfmzSTU8Im60xCCMa88g==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:msEryBEPAyIfuk5CVXMLONFSpKR71WZtdnvhDTXJwg==,iv:bMjT0t8O2VGfZW7xsv/CuHpsCKswYil+3TxwriHI158=,tag:sI1yjDzntSLE1gt7GjpihQ==,type:str]
            AWS_ENDPOINT: ENC[AES256_GCM,data:BKgPEMjEnBHk/xI+s9DgnxFR3JHdccJtfnc3TxC3IAY7vCm17nIuVKCKAMq4,iv:6LAjeEyvCaswPqIykI+AaKi1F/LqyW6vrP2wxIbLADc=,tag:BWnd6NUjAb5jYzvojYlX0w==,type:str]
            WALE_S3_ENDPOINT: ENC[AES256_GCM,data:bS5cz1Rx2z4QckkWISV/2uDef0IYQ2xR9YRJ64Vor3KyBXTbGcOdCY8FO8cc5ii/9iw=,iv:/usJ/xIiyN0AuZc/gcsmnBjkcdJYl627xD/ehrs5D+A=,tag:EQW600JZkYCS8emfuI90Rw==,type:str]
            CLONE_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:NEFCBL50BZ+HS+k7/yV2MLI6J2GM8RgPaA==,iv:SQHm+x5kWh4yC0cz0C8kweVb4FsXAnVdQk9b0+aW0No=,tag:omLLKvu5n7Ulj05Wy80EaA==,type:str]
            CLONE_AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Hg+5NGvybOLymiLknXLOqN/BDoEEvrKOLK7aOs4rTg==,iv:Sk/VUDPUxbfEvn2xkd2qpdWH0h/mM5mMNscd1DDJ9S4=,tag:xlEASKCWmkiZ8vCI1R5dhw==,type:str]
            CLONE_AWS_ENDPOINT: ENC[AES256_GCM,data:nwX02+gUzUItq8jkOJIDaNjFDaP12px0tqIGXo3eWmnfkKbqgr4U5Zjd8Wwv,iv:yMMwB4YB1ea3NVi5H20XdkpCZxXYGHblnMVBU/2mrnM=,tag:zWEzu9ZOHYXucsMygDg15g==,type:str]
        - name: admin-password
          stringData:
            ADMIN_PASSWORD: ENC[AES256_GCM,data:JRlL/ZEHSTFX8PFwTCn9vg2hC7j5T5OokvHqto2YCbagWAKM4Uoh8PBxP/UdWTedNnKtCxIJ6IrXVkvdZb1VtA==,iv:V+ZX2kH74hidOIsVRO5oUrO+VV++UZ9gxHBpOVsu5FQ=,tag:zAae9gZh+ywODQGd7kLJvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kztlwk25hdsy8s2gqlkx4aucdwss5zfaejadtnv5s2zd7vmslq0s8gqltu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQTArRkRrbVBjQVlUQUxM
            ZTFCUkVOVmVVMExhdUp4bjlld0lsbVhaS200ClZMS0RUZlh2V3IxS3hiLytRb2pu
            cG5sVDljb0kxWXRoN1YwblV2TG1mcWMKLS0tIEdHYVREN3VjZWpMNzdaUkpMR1Fm
            Ymx1Z3piUzBjcE9Bb2ptMDh4TW5FVG8KTtx0e2rnVAHtCmVWqir0fjb518aVTJnq
            gXQlUj47Tjp63I0TcdZ07cv+qm53xG3zxSbXY53muW9zNzHXJ+327w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-05T19:36:43Z"
    mac: ENC[AES256_GCM,data:Hs1If4Q17anqFB9pwSlXE0jl/ofEUm/H7cVYzRrFiWP3pWRwo8t+pD2czKvh1lsjiuVF1RZG8Xymx5I/JAcBZYkkcEUtWJbc1eGCMmZuWJr/a7xOVeee1O30rf71cz5Sh+rRmOWgCf+2zOFbTfOyobwRYjPt0mREfpe8/++Myeo=,iv:xudKS5e+c/7OfDFpiHqbVo4hcqkZyVvGszR15OpOqVg=,tag:V6BmViFX4GMeeuAwRX+Pug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
