apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: secrets
    namespace: miniflux
spec:
    secretTemplates:
        - name: postgres-pod-secrets
          stringData:
            AWS_ACCESS_KEY_ID: 00375f63a749b92000000000f
            AWS_SECRET_ACCESS_KEY: K0038JV02rGfUezdL15lsgl0RmQeI9w
            AWS_ENDPOINT: https://s3.eu-central-003.backblazeb2.com:443
            WALE_S3_ENDPOINT: https+path://s3.eu-central-003.backblazeb2.com:443
            CLONE_AWS_ACCESS_KEY_ID: 00375f63a749b92000000000f
            CLONE_AWS_SECRET_ACCESS_KEY: K0038JV02rGfUezdL15lsgl0RmQeI9w
            CLONE_AWS_ENDPOINT: https://s3.eu-central-003.backblazeb2.com:443
