apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: miniflux
  namespace: miniflux
spec:
  endpoints:
  - targetPort: 8080
  jobLabel: miniflux
  selector:
    matchLabels:
      app.kubernetes.io/instance: miniflux
