# https://github.com/morremeyer/charts/blob/main/charts/generic/values.yaml

command:
- /bin/ash
- -c
- |-
  set -ueo pipefail
  export DATABASE_URL=postgres://miniflux:$DB_PASS@miniflux-db/miniflux
  exec /usr/bin/miniflux
env:
  ADMIN_USERNAME: admin
  BASE_URL: https://miniflux.samcday.com
  CREATE_ADMIN: "1"
  INVIDIOUS_INSTANCE: invidious.samcday.com
  METRICS_ALLOWED_NETWORKS: 0.0.0.0/0
  METRICS_COLLECTOR: "1"
  RUN_MIGRATIONS: "1"
envValueFrom:
  ADMIN_PASSWORD:
    secretKeyRef:
      name: admin-password
      key: ADMIN_PASSWORD
  DB_PASS:
    secretKeyRef:
      name: miniflux.miniflux-db.credentials.postgresql.acid.zalan.do
      key: password
image:
  repository: miniflux/miniflux
  tag: 2.0.35
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
  className: nginx
  hosts:
  - host: miniflux.samcday.com
    paths:
    - path: /
  tls:
  - hosts:
    - miniflux.samcday.com
    secretName: certificate
livenessProbe:
  httpGet:
    path: /healthcheck
    port: 8080
readinessProbe: ~
replicaCount: 2
service:
  name: miniflux
  targetPort: 8080
