apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: miniflux
  namespace: miniflux
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: miniflux-generic
  updatePolicy:
    updateMode: Auto
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: miniflux-db
  namespace: miniflux
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: miniflux-db
  updatePolicy:
    updateMode: Auto
