---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-exporter
  namespace: flux-system
spec:
  chart:
    spec:
      chart: prometheus-postgres-exporter
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: 2.4.0
  interval: 1m0s
  releaseName: synapse-postgres-exporter
  targetNamespace: synapse
  timeout: 1m
  values:
    serviceMonitor:
      enabled: true
      namespace: monitoring
      labels:
        release: monitoring
    config:
      datasource:
        host: synapse-db
        passwordSecret:
          name: postgres.synapse-db.credentials.postgresql.acid.zalan.do
          key: password
        sslmode: require
