apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: synapse-db
spec:
  teamId: synapse
  volume:
    size: 10Gi
    storageClass: openebs-hostpath
  numberOfInstances: 2
  users:
    synapse_user: []
    signal_user: []
    whatsapp_user: []
  databases:
    synapse: synapse_user
    signal: signal_user
    whatsapp: whatsapp_user
  postgresql:
    version: "13"
  patroni:
    initdb:
      encoding: UTF8
      locale: C
  enableLogicalBackup: false
