apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: synapse
  name: synapse
  namespace: synapse
spec:
  ports:
  - port: 8008
    protocol: TCP
    targetPort: 8008
  selector:
    app: synapse
status:
  loadBalancer: {}
