---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hcloud-fip-k8s
  namespace: flux-system
spec:
  chart:
    spec:
      chart: hcloud-fip-k8s
      sourceRef:
        kind: HelmRepository
        name: hcloud-fip-k8s
      version: 0.0.13
  interval: 1h
  releaseName: hcloud-fip-k8s
  targetNamespace: kube-system
  upgrade:
    crds: CreateReplace
  valuesFrom:
  - kind: ConfigMap
    name: hcloud-fip-k8s-values
