apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-user
  namespace: etcd
spec:
  secretName: root-user
  privateKey:
    algorithm: ECDSA
    size: 256
  usages: [client auth]
  commonName: root
  issuerRef:
    name: etcd-issuer
    kind: Issuer
    group: cert-manager.io
