---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1h
  path: ./flux-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: personal-infrastructure
  timeout: 30s
