---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 15m0s
  path: ./ingress-nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: personal-infrastructure
  timeout: 2m0s
  wait: true
