---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: playkube
  namespace: flux-system
spec:
  interval: 1h
  path: ./playkube
  prune: true
  sourceRef:
    kind: GitRepository
    name: personal-infrastructure
  timeout: 30s
  wait: true
