apiVersion: apps/v1
kind: Deployment
metadata:
  name: invidious
  namespace: invidious
  labels:
    app: invidious
spec:
  replicas: 2
  selector:
    matchLabels:
      app: invidious
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      labels:
        app: invidious
    spec:
      enableServiceLinks: false
      containers:
      - image: quay.io/invidious/invidious:6c73614a47a5a88df45aa32fadb64e85595d2a18
        name: invidious
        env:
        - name: INVIDIOUS_CONFIG_FILE
          value: /config/config.yaml
        readinessProbe:
          httpGet:
            path: /api/v1/stats
            port: 3000
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /api/v1/stats
            port: 3000
          periodSeconds: 5
          failureThreshold: 2
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 250m
            memory: 192Mi
          limits:
            memory: 256Mi
        volumeMounts:
        - name: config
          mountPath: /config
      initContainers:
      - name: config
        image: supinf/envsubst
        command:
        - sh
        - -c
        - |-
          envsubst < /config-template/config.yaml > /config/config.yaml
        env:
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kemal.invidious-db.credentials.postgresql.acid.zalan.do
              key: password
        - name: CAPTCHA_KEY
          valueFrom:
            secretKeyRef:
              name: invidious
              key: anticaptcha
        - name: HMAC_KEY
          valueFrom:
            secretKeyRef:
              name: invidious
              key: hmac
        volumeMounts:
        - name: config-template
          mountPath: /config-template
        - name: config
          mountPath: /config
      volumes:
      - name: config-template
        configMap:
          name: config
      - name: config
        emptyDir: {}
