apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: invidious
  name: invidious
spec:
  replicas: 2
  selector:
    matchLabels:
      app: invidious
  template:
    metadata:
      labels:
        app: invidious
    spec:
      enableServiceLinks: false
      containers:
      - image: quay.io/invidious/invidious:fc2b9031d4850e7ed8eb24e388aeae38b4eb2762
        name: invidious
        env:
        - name: INVIDIOUS_CONFIG_FILE
          value: /config/config.yaml
        # Stats endpoint is cheap, check it often for readiness check.
        readinessProbe:
          httpGet:
            path: /api/v1/stats
            port: 3000
          periodSeconds: 5
        # Check connectivity to Youtube less frequently for liveness check.
        livenessProbe:
          httpGet:
            path: /api/v1/comments/jNQXAC9IVRw
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 60
          failureThreshold: 2
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: config
          mountPath: /config
      initContainers:
      - name: config
        image: alpine:3.15.0
        command:
        - sh
        - -c
        - |-
          apk add gettext
          envsubst < /config-template/config.yaml > /config/config.yaml
        env:
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kemal.invidious-db.credentials.postgresql.acid.zalan.do
              key: password
        - name: CAPTCHA_KEY
          valueFrom:
            secretKeyRef:
              name: invidious
              key: anticaptcha
        - name: HMAC_KEY
          valueFrom:
            secretKeyRef:
              name: invidious
              key: hmac
        volumeMounts:
        - name: config-template
          mountPath: /config-template
        - name: config
          mountPath: /config
      volumes:
      - name: config-template
        configMap:
          name: config
      - name: config
        emptyDir: {}
