apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: config
  namespace: invidious
  files: [config.yaml]
resources:
- certificate.yaml
- deployment.yaml
- ingress.yaml
- limit-range.yaml
- namespace.yaml
- pdb.yaml
- postgres.yaml
- postgres-exporter.yaml
- secrets.yaml
- service.yaml
- vpa.yaml
