apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: invidious
resources:
- namespace.yaml
- certificate.yaml
- postgres.yaml
- secrets.yaml
- deployment.yaml
- ingress.yaml
- service.yaml

configMapGenerator:
- name: config
  files: [config.yaml]
