apiVersion: v1
kind: LimitRange
metadata:
  name: happy-cluster
  namespace: flux-system
spec:
  limits:
  - default:
      cpu: 1000m
    defaultRequest:
      cpu: 10m
    max:
      cpu: 1000m
    min:
      cpu: 10m
    type: Container
