apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: postgres
spec:
    secretTemplates:
        - name: postgres
          stringData:
            password: ENC[AES256_GCM,data:xg3665fdMNlzNaR0O5w=,iv:K8AzTm+azWZr6ER8rsTTo32Eg9ejmDd5bK9SIwiFC4g=,tag:vYN8hbzZ7EaxXgfUnwJxKQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kztlwk25hdsy8s2gqlkx4aucdwss5zfaejadtnv5s2zd7vmslq0s8gqltu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQ09za1Joc29uY2N5S0JG
            L0RMQVJ2ZjFIeXlncDJMZkZZanZ1c0s5UFVVClF6b1pzQ1BLK2E4QXlMMG1QNXRC
            bmFxL2k3Zm5Wd1F3WmhKb3Q3YnU0L1UKLS0tIFNSa1VGY0lEN0hmWkZSd1BWUmM2
            VERGWm9sK3pwUjNoWXBwZnFxQUQxL00Kkie1Lupsd3bR7sw856aV/Ro3FAPH/Nn2
            ULK8FUa1xAdF/eMsDxb/OVw3m3AjIVscB/7hDYEAlv4K7etoth6xvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-28T09:52:41Z"
    mac: ENC[AES256_GCM,data:XBMH5RBVNY4/6iw+rH0LONMVo7PwH54hy3yWHUjC50fqPMHU+0hYlcAjogGEX0X1UeYELJGiZftznvC3Y5cXgD2svs+6bn/QzYNdopaMksCpQ1krQRPOyBI3I/Fd53aJaekowogjcSCQe3WrfRaBBv6wajk5SNn3mXlcq3/XOh8=,iv:aEw3fMHT5zrwV1s3dqhUepHnkiDWfCbkGpQfKwMC9yg=,tag:9FuCW1sj9XLsYK7jsTd9oA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
