apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: secrets
spec:
    secretTemplates:
        - name: postgres
          stringData:
            password: ENC[AES256_GCM,data:xg3665fdMNlzNaR0O5w=,iv:K8AzTm+azWZr6ER8rsTTo32Eg9ejmDd5bK9SIwiFC4g=,tag:vYN8hbzZ7EaxXgfUnwJxKQ==,type:str]
        - name: invidious
          stringData:
            hmac: ENC[AES256_GCM,data:1f5jDDi3bFj/oY+14h+KKYmgc0IggQMSxyTOAtnVo/lUXszjuQ78ehXx9/x9qg==,iv:OP739dx9Eu3wSnI4EX+ilOvUJA5IzI20s2E4sDFbRpE=,tag:kLKHWo+cpY7Z/6VVLeMEqw==,type:str]
            anticaptcha: ENC[AES256_GCM,data:53obRg/B97Rz9E+BUiH8rl0IvpSiJ6FXkpUS8mfEBNs=,iv:CEIpRwyn3mP2jZ4cZf/uXRzjFT7/olGx1lpCQAxL7EQ=,tag:1TfcV6sz7OtJRmLBLOrb6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kztlwk25hdsy8s2gqlkx4aucdwss5zfaejadtnv5s2zd7vmslq0s8gqltu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQ09za1Joc29uY2N5S0JG
            L0RMQVJ2ZjFIeXlncDJMZkZZanZ1c0s5UFVVClF6b1pzQ1BLK2E4QXlMMG1QNXRC
            bmFxL2k3Zm5Wd1F3WmhKb3Q3YnU0L1UKLS0tIFNSa1VGY0lEN0hmWkZSd1BWUmM2
            VERGWm9sK3pwUjNoWXBwZnFxQUQxL00Kkie1Lupsd3bR7sw856aV/Ro3FAPH/Nn2
            ULK8FUa1xAdF/eMsDxb/OVw3m3AjIVscB/7hDYEAlv4K7etoth6xvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-28T20:20:13Z"
    mac: ENC[AES256_GCM,data:iGvjAWEyWvbM0N8so8NUkahgrsxHUZtv5Nqg8MZHnJSoOhy6ZcPRSC6AiGpA0O2SKIetBK2NIqjlINxSilzFl0IVTIgC0cWT/sHQvcaRXQnYtJXmK1XwX673Gj4jiJPb5cQhznGO8He7WGGSDkjLmfQfiF31hJn9XEGZE7GLlHI=,iv:nITpf8E9qLtiVRP19KnaJYuNeWg933cf3knRcke/k+4=,tag:j2gr1v52uvxE2mEOAlzKAw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
