apiVersion: batch/v1
kind: CronJob
metadata:
  name: cloud-init-generator
  namespace: kube-system
spec:
  jobTemplate:
    metadata:
      name: cloud-init-generator
    spec:
      template:
        metadata:
        spec:
          tolerations:
            - effect: NoSchedule
              key: node-role.kubernetes.io/master
          containers:
          - image: samcday/cloud-init-generator:c585d22839fcec1c6846ac341ced1a231ac4912ac0c03c9c46bc2f6e477a9b36
            name: cloud-init-generator
            command: ["/bin/ash", "/script/update-cloud-init.sh"]
            volumeMounts:
            - name: script
              mountPath: /script
          serviceAccountName: cloud-init-generator
          volumes:
          - name: script
            configMap:
              name: cloud-init-generator-script
          restartPolicy: OnFailure
  schedule: 0 0 * * *
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-init-generator
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cloud-init-generator
  namespace: kube-system
rules:
- apiGroups: [""]
  resources: [configmaps]
  resourceNames: [kubeadm-config]
  verbs: [get]
- apiGroups: [""]
  resources: [secrets]
  resourceNames: [discovery-token-hash, hcloud, hcloud-cloud-init]
  verbs: [get]
- apiGroups: [""]
  resources: [secrets]
  verbs: [create]
- apiGroups: [""]
  resources: [secrets]
  resourceNames: [hcloud-cloud-init]
  verbs: [patch]
- apiGroups: [apps]
  resources: [deployments]
  resourceNames: [cluster-autoscaler]
  verbs: [get, patch]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloud-init-generator
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cloud-init-generator
subjects:
- kind: ServiceAccount
  name: cloud-init-generator
  namespace: kube-system
