id: signal
as_token: ${SIGNAL_AS_TOKEN}
hs_token: ${SIGNAL_HS_TOKEN}
namespaces:
    users:
    - exclusive: true
      regex: '@signal_.*:matrix\.samcday\.com'
    - exclusive: true
      regex: '@signalbot:matrix\.samcday\.com'
    aliases: []
url: http://mautrix-signal:29328
sender_localpart: ${SIGNAL_SENDER_LOCALPART}
rate_limited: false
