---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: flux-system
spec:
  chart:
    spec:
      chart: openebs
      sourceRef:
        kind: HelmRepository
        name: openebs
      version: 3.0.6
  install:
    createNamespace: true
  interval: 30m
  releaseName: openebs
  targetNamespace: openebs
  values:
    ndm:
      enabled: false
    ndmOperator:
      enabled: false
