---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: 34.10.0
  interval: 1h
  releaseName: monitoring
  valuesFrom:
  - kind: ConfigMap
    name: kube-prometheus-stack-values
  - kind: Secret
    name: kube-prometheus-stack-secrets
    valuesKey: deadmanssnitch_url
    targetPath: alertmanager.config.receivers[0].webhook_configs[0].url
  - kind: Secret
    name: kube-prometheus-stack-secrets
    valuesKey: pagerduty_key
    targetPath: alertmanager.config.receivers[1].pagerduty_configs[0].service_key
