apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: kube-prometheus-stack-secrets
    namespace: monitoring
spec:
    secretTemplates:
        - name: kube-prometheus-stack-secrets
          stringData:
            deadmanssnitch_url: ENC[AES256_GCM,data:b6uBVNKhoO2GjhZHglRGBQ8ukXyM8S8teW4iFQ==,iv:mb0TJKktYhlL4upsHpCB4WowEFfDSFiASrtzpUgRQYI=,tag:dagOQuxSXJ5zt4yLnf5THQ==,type:str]
            pagerduty_key: ENC[AES256_GCM,data:BKGzQY4KcRwpMGldd+KK8WcxPBGiDgaR8yNW2+lyuL8=,iv:6YLH4FHPHTh/a/PDbdgW8tjxHwJ3SF/gjkJapqYXN+g=,tag:wtoKSycphn1hrUqO2pwzCA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kztlwk25hdsy8s2gqlkx4aucdwss5zfaejadtnv5s2zd7vmslq0s8gqltu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5blpDYmtJQTRiREpMR1U3
            R2dHbEFTeFZyS1lETGFRZUlkTU90L0JuMGxnCmZJRFp5eUgwdDZIRloyOHZCUjhV
            VlM2TU4yKzA5UzU2RlptRE83ZUk1SGcKLS0tIE1vVk5PR0FUZCt2N0lyTXI0bWtK
            Ym5tcjh6UWVtZUxPVUlKTEsrbW14MjAKgxKWTIUF6yb8zRYBSABYGFw7lujeCIcS
            I6NEbJXN09aU+mfh0chYRIWF7bKhTdYF0OtgOnN/9rbK9BLrBY8Xag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-05T08:17:22Z"
    mac: ENC[AES256_GCM,data:11FHJTqUD5pxXVVL1h/Qwlok+vi8yjglMqQcPZnJA1ndSshqIEyH8pqI1E4Lv7p3uZEz4XTMgejnSXN9Oda8vfzAoK6FkQXp1B0T/8EaWO14+pDc8evAHinpRCNh3nNKFDDHXaY/69ko5raRwiitgbsGUk6jZjWF96OJNr0lwD8=,iv:9bOdhjieaznNiQJD8jB6hcL50q28F/Z0zy69pzgRrQU=,tag:wCUOjsLCSFFkeKU74EHRHg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
