# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml

kubeApiServer:
  enabled: false
kubeControllerManager:
  serviceMonitor:
    insecureSkipVerify: true
kubeEtcd:
  service:
    port: 2381
    targetPort: 2381
kubeProxy:
  enabled: false
kubeScheduler:
  serviceMonitor:
    insecureSkipVerify: true
prometheus:
  prometheusSpec:
    enableAdminAPI: true
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    resources:
      limits:
        memory: 2048Mi
    retention: 30d
    retentionSize: 30GB
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: hcloud-volumes
          accessModes: [ReadWriteOnce]
          resources:
            requests:
              storage: 50Gi
    walCompression: true
  service:
    annotations:
      external-dns.alpha.kubernetes.io/internal-hostname: prometheus.samcday.com
alertmanager:
  config:
    route:
      routes:
      - matchers:
        - alertname = Watchdog
        receiver: deadmanssnitch
        group_wait: 0s
        repeat_interval: 30m
      - matchers:
        - alertname != Watchdog
        receiver: pagerduty
    receivers:
    - name: deadmanssnitch
      webhook_configs:
      - url: "" # Set in secrets
    - name: pagerduty
      pagerduty_configs:
      - service_key: "" # Set in secrets
    - name: "null"
  service:
    annotations:
      external-dns.alpha.kubernetes.io/internal-hostname: alertmanager.samcday.com

# https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
grafana:
  service:
    annotations:
      external-dns.alpha.kubernetes.io/internal-hostname: grafana.samcday.com

prometheus-node-exporter:
  prometheus:
    monitor:
      relabelings:
      - sourceLabels: [__meta_kubernetes_pod_node_name]
        targetLabel: instance
        replacement: $1
        action: replace
