---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-receiver
  namespace: flux-system
spec:
  interval: 1h
  path: ./core/flux-receiver
  prune: true
  sourceRef:
    kind: GitRepository
    name: personal-infrastructure
  timeout: 2m0s
