---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 15m0s
  path: ./core/kube-prometheus-stack
  prune: false
  sourceRef:
    kind: GitRepository
    name: personal-infrastructure
  timeout: 2m0s
  wait: true

