apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cert-manager.yaml
- cluster-autoscaler.yaml
- flux.yaml
- flux-receiver.yaml
- hcloud-controller-manager.yaml
- hcloud-csi-driver.yaml
- ingress-nginx.yaml
- kube-prometheus-stack.yaml
- loki.yaml
- metrics-server.yaml
- openebs.yaml
- postgres-operator.yaml
- sops-secrets-operator.yaml
- system-upgrade-controller.yaml
- tailscale.yaml
- vertical-pod-autoscaler.yaml
