---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  interval: 15m0s
  path: ./core/metrics-server
  prune: false
  sourceRef:
    kind: GitRepository
    name: personal-infrastructure
  timeout: 2m0s
  wait: true

