---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vertical-pod-autoscaler
  namespace: flux-system
spec:
  interval: 15m0s
  path: ./core/vertical-pod-autoscaler
  prune: false
  sourceRef:
    kind: GitRepository
    name: personal-infrastructure
  timeout: 2m0s
  wait: true

