# https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph-cluster/values.yaml
cephBlockPools: null
cephFileSystems: null
cephObjectStores: null
cephClusterSpec:
  cephVersion:
    image: quay.io/ceph/ceph:v16.2.7
  dashboard:
    enabled: true
  dataDirHostPath: /var/lib/rook
  mgr:
    count: 1
  mon:
    count: 1
    allowMultiplePerNode: false
    volumeClaimTemplate:
      spec:
        storageClassName: openebs-hostpath  
        resources:
          requests:
            storage: 10Gi
  placement:
    mgr:
      nodeAffinity: &affinity
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
      tolerations: &tolerations
      - key: node-role.kubernetes.io/master
        operator: Exists
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
    mon:
      nodeAffinity: *affinity
      tolerations: *tolerations
  resources:
    mgr:
      limits:
        memory: 512Mi
    osd:
      limits:
        memory: 512Mi
  storage:
   storageClassDeviceSets:
    - name: hcloud
      count: 2
      portable: false
      encrypted: false
      volumeClaimTemplates:
      - metadata:
          name: data
        spec:
          resources:
            requests:
              storage: 10Gi
          storageClassName: hcloud-volumes
          volumeMode: Block
          accessModes:
            - ReadWriteOnce
monitoring:
  enabled: true
toolbox:
  enabled: true
  tolerations: *tolerations
