monitoring:
  enabled: true
toolbox:
  tolerations: &tolerations
  - key: node-role.kubernetes.io/master
    effect: NoSchedule
    operator: Exists
  - key: node-role.kubernetes.io/control-plane
    effect: NoSchedule
    operator: Exists
