---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sops-secrets-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: sops-secrets-operator
      sourceRef:
        kind: HelmRepository
        name: sops-secrets-operator
      version: 0.10.3
  crds: CreateReplace
  interval: 1h
  releaseName: sops-secrets-operator
  targetNamespace: kube-system
  valuesFrom:
  - kind: ConfigMap
    name: sops-secrets-operator-values
