---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: sops-secrets-operator
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://isindir.github.io/sops-secrets-operator/

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sops-secrets-operator
  namespace: flux-system
spec:
  timeout: 1m
  chart:
    spec:
      chart: sops-secrets-operator
      sourceRef:
        kind: HelmRepository
        name: sops-secrets-operator
      version: 0.10.2
  interval: 1m0s
  releaseName: sops-secrets-operator
  targetNamespace: kube-system
  values:
    extraEnv:
    - name: SOPS_AGE_KEY_FILE
      value: /age-key/age-key.txt
    secretsAsFiles:
    - name: age-key
      mountPath: /age-key
      secretName: age-key
