apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
apiServer:
  extraArgs:
    authorization-mode: Node,RBAC
    audit-policy-file: /etc/kubernetes/audit-policy.yaml
    audit-log-maxage: "1"
    audit-log-maxbackup: "1"
    audit-log-maxsize: "5"
    audit-log-path: /var/log/kubernetes/audit/audit.log
    kubernetes-service-node-port: "31443"
  extraVolumes:
  - name: audit-log
    hostPath: /var/log/kubernetes/audit/
    mountPath: /var/log/kubernetes/audit/
    pathType: DirectoryOrCreate
    readOnly: false
  - name: audit-policy
    hostPath: /etc/kubernetes/audit-policy.yaml
    mountPath: /etc/kubernetes/audit-policy.yaml
    pathType: File
    readOnly: true
  timeoutForControlPlane: 4m0s
certificatesDir: /etc/kubernetes/pki
clusterName: personal
controlPlaneEndpoint: ${loadbalancer_ip}:6443
controllerManager:
  extraArgs:
    bind-address: 0.0.0.0
dns:
  type: CoreDNS
etcd:
  local:
    dataDir: /var/lib/etcd
    extraArgs:
      listen-metrics-urls: http://0.0.0.0:2381
imageRepository: k8s.gcr.io
kubernetesVersion: ${kube_version}
networking:
  dnsDomain: cluster.local
  podSubnet: 10.98.0.0/15
  serviceSubnet: 10.97.0.0/16
scheduler:
  extraArgs:
    bind-address: 0.0.0.0
