apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: openebs-values
  namespace: flux-system
  files: [openebs/values.yaml]
- name: hcloud-fip-k8s-values
  namespace: flux-system
  files: [hcloud-fip-k8s/values.yaml]
- name: postgres-operator-values
  namespace: flux-system
  files: [postgres-operator/values.yaml]

- name: kubeadm-config
  namespace: kube-system
  files: [ClusterConfiguration=kubeadm-config.yaml]
  options: {disableNameSuffixHash: true}
resources:
- ../kustomizeconfig/
- cert-manager/
- cilium/
- cluster-autoscaler/
- external-dns/
- hcloud-controller-manager/
- hcloud-csi-driver/
- hcloud-fip-k8s/helm-release.yaml
- ingress-nginx/
- limit-range.yaml
- metrics-server/
- openebs/helm-release.yaml
- postgres-operator/helm-release.yaml
- sops-secrets-operator/
- svc-kube-public.yaml
- system-upgrade-controller/
- tailscale/
- vertical-pod-autoscaler/
