apiVersion: v1
kind: Service
metadata:
  name: kube-public
  namespace: kube-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: kube.samcday.com
spec:
  externalIPs:
  - 78.46.240.242
  ports:
  - name: kube
    port: 6443
    protocol: TCP
    targetPort: 6443
  selector:
    component: kube-apiserver
