---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: charts/postgres-operator
      sourceRef:
        kind: GitRepository
        name: postgres-operator
        namespace: flux-system
  install:
    createNamespace: true
  interval: 30m
  releaseName: postgres-operator
  targetNamespace: postgres-operator
  valuesFrom:
  - kind: ConfigMap
    name: postgres-operator-values
