---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: postgres-operator
      version: 1.7.1
      sourceRef:
        kind: HelmRepository
        name: postgres-operator
  install:
    createNamespace: true
  interval: 30m
  releaseName: postgres-operator
  targetNamespace: postgres-operator
  valuesFrom:
  - kind: ConfigMap
    name: postgres-operator-values
