---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: postgres-operator
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    tag: v1.7.1
  url: https://github.com/zalando/postgres-operator
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/
