---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  chart:
    spec:
      chart: cilium
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      version: 1.12.2
  interval: 1h
  releaseName: cilium
  valuesFrom:
  - kind: ConfigMap
    name: cilium-values
