controller:
  kind: DaemonSet
  config:
    use-proxy-protocol: true
  extraArgs:
    enable-ssl-passthrough: ""
  tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
  service:
    type: NodePort
    nodePorts:
      http: 32080
      https: 32443
    externalIPs: [49.12.17.240] # Could be nice to pull this dynamically from a CM set by bootstrap.sh, or something. 
    externalTrafficPolicy: Local
