apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
configMapGenerator:
- name: cloud-init-generator-script
  files: [cloud-init-generator/update-cloud-init.sh]
resources:
- cluster-autoscaler.yaml
- cloud-init-generator.yml
- vpa.yaml
