---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-exporter
  namespace: flux-system
spec:
  chart:
    spec:
      chart: prometheus-postgres-exporter
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: 2.4.0
  interval: 30m
  releaseName: invidious-postgres-exporter
  targetNamespace: invidious
  values:
    serviceMonitor:
      enabled: true
      namespace: invidious
    config:
      datasource:
        host: invidious-db
        passwordSecret:
          name: postgres.invidious-db.credentials.postgresql.acid.zalan.do
          key: password
        sslmode: require
