apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: secrets
spec:
    secretTemplates:
        - name: postgres-pod-secrets
          stringData:
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:3mfdgMZYPi54FqjjYdzkeZi5NSBJV1mp2A==,iv:U2YXgXUBS7J7xoOWcbSn26hRvVwkdN1psG4cv2N2/3o=,tag:xCL1AMvl7yLTh9ugGiZEgA==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:UVl72PPD60XeqX3fp+WISilwh2a7IoPV3cfX8CEbDA==,iv:1CTDpIQUCIjwpdCEdM8TikjJO91Nl5QVDLgn/K2W6ZQ=,tag:seyjYFQm1j6x+j3ppRZa3Q==,type:str]
            AWS_ENDPOINT: ENC[AES256_GCM,data:pvW7G/m5FbhGtb7x3XHPIaZZrYokPX0PPRZXcVCHZJKk57Ag0DU6ZZW3wptP,iv:hTB3mVt0GjLhClFtbPleDcM4GQyQsiQVVbXPwIab10E=,tag:bU8tpa/A/WFmACnkCNG7yg==,type:str]
            WALE_S3_ENDPOINT: ENC[AES256_GCM,data:/ghuJ3fSfCwqYvHbCe2kjjornP4BwhpqChQBCih1muxtbq0n6RJtYxaZdARcLuq3bOI=,iv:KwUIwJJjY1d6xdT1jYu7PmV+WDxiqTHleSACKZOZQx4=,tag:dz31Z5ISih6abbQwvLxW6A==,type:str]
            CLONE_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:DjsepypuNoiP4mAuNwJUTlzKe8htahvXiw==,iv:wR9kw6Mp8ma156ZRmWJqacxAEgezjwiNm+dtyFRjTJY=,tag:egZqrUx566U8OFvQJH/tPA==,type:str]
            CLONE_AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:vnjWDyN6MM3dvz6Ebp5hiTTD4Ug/zHot0kYJ+3E8Cw==,iv:66t0E5ebvPWJZQMpf8YD9ib/E7r2+AMsffrk6p6It6o=,tag:GyiXerULOG/DAzqbT4JE+g==,type:str]
            CLONE_AWS_ENDPOINT: ENC[AES256_GCM,data:dHLTFOEk1wBFEcf9OkOckBdWbDXiGhinEX5AQAvnbjJcN6607GlitKNuql6x,iv:C7VptHlUzyx4jJMlxsGABziw2XlatLLkrsphzQHge2Q=,tag:q+kpL2ugr/mMZUu1L0woKg==,type:str]
        - name: invidious
          stringData:
            hmac: ENC[AES256_GCM,data:1f5jDDi3bFj/oY+14h+KKYmgc0IggQMSxyTOAtnVo/lUXszjuQ78ehXx9/x9qg==,iv:OP739dx9Eu3wSnI4EX+ilOvUJA5IzI20s2E4sDFbRpE=,tag:kLKHWo+cpY7Z/6VVLeMEqw==,type:str]
            anticaptcha: ENC[AES256_GCM,data:53obRg/B97Rz9E+BUiH8rl0IvpSiJ6FXkpUS8mfEBNs=,iv:CEIpRwyn3mP2jZ4cZf/uXRzjFT7/olGx1lpCQAxL7EQ=,tag:1TfcV6sz7OtJRmLBLOrb6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kztlwk25hdsy8s2gqlkx4aucdwss5zfaejadtnv5s2zd7vmslq0s8gqltu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQ09za1Joc29uY2N5S0JG
            L0RMQVJ2ZjFIeXlncDJMZkZZanZ1c0s5UFVVClF6b1pzQ1BLK2E4QXlMMG1QNXRC
            bmFxL2k3Zm5Wd1F3WmhKb3Q3YnU0L1UKLS0tIFNSa1VGY0lEN0hmWkZSd1BWUmM2
            VERGWm9sK3pwUjNoWXBwZnFxQUQxL00Kkie1Lupsd3bR7sw856aV/Ro3FAPH/Nn2
            ULK8FUa1xAdF/eMsDxb/OVw3m3AjIVscB/7hDYEAlv4K7etoth6xvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-31T10:59:05Z"
    mac: ENC[AES256_GCM,data:iDbljY1DgG56hHTvKlrSXFWEKoVdWs96BmckNvyZjQOX7AvR4PteCmtBqG1HoAxLUfSgTVDrvElTwjtRiIxfEIQn9xUdNT6+zdXMfZEWmGz5H1HnXyhtWTJNlCWEthg+5RS7GYHXufhoCLohqsnkyEhrjBn/k69YiUvcuZA3dN8=,iv:ESyAZa9bx23m/SJYHMdQKUoIBrx2CdrWyNHut+ZOxmI=,tag:7OfrA6BNGfRSCXX0OCknjA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
