apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/hetznercloud/csi-driver?ref=f4d4d5c59d8609b25b7168bcf91f22ec0c957c9e
- vpa.yaml
patches:
- target:
    group: apps
    version: v1
    kind: DaemonSet
    name: hcloud-csi-node
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/1/env/3/valueFrom/secretKeyRef
      value:
        name: hcloud
        key: HCLOUD_TOKEN
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: hcloud-csi-controller
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/3/env/4/valueFrom/secretKeyRef
      value:
        name: hcloud
        key: HCLOUD_TOKEN
