apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: hcloud-csi-node
  namespace: kube-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: DaemonSet
    name: hcloud-csi-node
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
    - containerName: "*"
      controlledValues: RequestsOnly
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: hcloud-csi-controller
  namespace: kube-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: hcloud-csi-controller
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
    - containerName: "*"
      controlledValues: RequestsOnly
