---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sops-secrets-operator
  namespace: kube-system
spec:
  chart:
    spec:
      chart: sops-secrets-operator
      sourceRef:
        kind: HelmRepository
        name: sops-secrets-operator
        namespace: flux-system
      version: 0.10.6
  interval: 1h
  releaseName: sops-secrets-operator
  upgrade:
    crds: CreateReplace
  valuesFrom:
  - kind: ConfigMap
    name: sops-secrets-operator-values
