---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: system-upgrade-plans
  namespace: kube-system
spec:
  interval: 1m0s
  path: ./kube-system/system-upgrade-controller/plans
  prune: true
  sourceRef:
    kind: GitRepository
    name: personal-infrastructure
    namespace: flux-system
