---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cilium
      sourceRef:
        kind: HelmRepository
        name: cilium
      version: v1.11.1
  interval: 1h
  releaseName: cilium
  storageNamespace: kube-system
  targetNamespace: kube-system
  valuesFrom:
  - kind: ConfigMap
    name: cilium-values
