apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
- ../../kustomizeconfig.yaml
configMapGenerator:
- name: cilium-values
  namespace: flux-system
  files: [values.yaml]
resources:
- helm-release.yaml