---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flux-sync
  namespace: flux-system
spec:
  chart:
    spec:
      chart: flux2-sync
      sourceRef:
        kind: HelmRepository
        name: fluxcd-community
      version: 0.3.6
  install:
    disableWait: true
  interval: 1h
  releaseName: personal-infrastructure
  targetNamespace: flux-system
  valuesFrom:
  - kind: ConfigMap
    name: flux-sync-values
