---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: fluxcd-community
  namespace: flux-system
spec:
  interval: 24h0m0s
  url: https://fluxcd-community.github.io/helm-charts
