---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flux
  namespace: flux-system
spec:
  chart:
    spec:
      chart: flux2
      sourceRef:
        kind: HelmRepository
        name: fluxcd-community
      version: 0.12.0
  install:
    disableWait: true
  interval: 1h
  releaseName: flux
  targetNamespace: flux-system
  valuesFrom:
  - kind: ConfigMap
    name: flux-values
