id: whatsapp
url: http://mautrix-whatsapp:29318
as_token: ${WA_AS_TOKEN}
hs_token: ${WA_HS_TOKEN}
sender_localpart: ${WA_SENDER_LOCALPART}
rate_limited: false
namespaces:
  users:
  - regex: ^@whatsapp_[0-9]+:matrix.samcday.com$
    exclusive: true
  - regex: ^@whatsappbot:matrix.samcday.com$
    exclusive: true
