id: telegram
as_token: ${TELE_AS_TOKEN}
hs_token: ${TELE_HS_TOKEN}
namespaces:
    users:
    - exclusive: true
      regex: '@telegram_.*:matrix\.samcday\.com'
    - exclusive: true
      regex: '@telegrambot:matrix\.samcday\.com'
    aliases:
    - exclusive: true
      regex: \#telegram_.*:matrix\.samcday\.com
url: http://mautrix-telegram:29317
sender_localpart: ${TELE_SENDER_LOCALPART}
rate_limited: false
