apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: kubeadm-kubelet-upgrade
  namespace: system-upgrade
spec:
  concurrency: 1
  nodeSelector:
    matchExpressions:
    - key: kubernetes.io/os
      operator: In
      values: [linux]
  serviceAccountName: system-upgrade
  version: '1.23.3'
  tolerations:
  - operator: Exists
  cordon: true
  upgrade:
    image: ubuntu:focal
    command:
    - bash
    - -c
    - |-
      set -uexo pipefail

      chroot /host bash <<UPGRADE
      set -uexo pipefail
      apt-mark unhold kubectl kubelet
      apt-get install -y kubectl=${SYSTEM_UPGRADE_PLAN_LATEST_VERSION}-00 kubelet=${SYSTEM_UPGRADE_PLAN_LATEST_VERSION}-00
      apt-mark hold kubectl kubelet

      systemctl daemon-reload
      systemctl restart kubelet
      UPGRADE

      for i in {0..2}; do
        sleep 3
        /host/usr/bin/kubectl wait --for=condition=Ready node/${SYSTEM_UPGRADE_NODE_NAME}
      done
