apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: kubeadm-upgrade
  namespace: system-upgrade
spec:
  concurrency: 1
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
  serviceAccountName: system-upgrade
  version: '1.23.3'
  tolerations:
  - operator: Exists
  drain: {}
  upgrade:
    image: ubuntu:focal
    command: [chroot, /host]
    args:
    - bash
    - -c
    - |-
      set -uexo pipefail
      export DEBIAN_FRONTEND=noninteractive
      apt-get update
      
      apt-mark unhold kubeadm
      apt-get install -y kubeadm=${SYSTEM_UPGRADE_PLAN_LATEST_VERSION}-00
      apt-mark hold kubeadm

      kubeadm upgrade node

      apt-mark unhold kubectl kubelet
      apt-get install -y kubectl=${SYSTEM_UPGRADE_PLAN_LATEST_VERSION}-00 kubelet=${SYSTEM_UPGRADE_PLAN_LATEST_VERSION}-00
      apt-mark hold kubectl kubelet

      systemctl daemon-reload
      systemctl restart kubelet
      export KUBECONFIG=/etc/kubernetes/admin.conf

      # Just to be safe ;)
      sleep 3
      kubectl wait --for=condition=Ready node/${SYSTEM_UPGRADE_NODE_NAME}
      sleep 3
      kubectl wait --for=condition=Ready node/${SYSTEM_UPGRADE_NODE_NAME}
      sleep 3
      kubectl wait --for=condition=Ready node/${SYSTEM_UPGRADE_NODE_NAME}
