---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vertical-pod-autoscaler
  namespace: flux-system
spec:
  chart:
    spec:
      chart: vertical-pod-autoscaler
      sourceRef:
        kind: HelmRepository
        name: cowboysysop
      version: 4.0.4
  install:
    createNamespace: true
  interval: 1h
  releaseName: vertical-pod-autoscaler
  targetNamespace: kube-system
  valuesFrom:
  - kind: ConfigMap
    name: vertical-pod-autoscaler-values
