---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: rook-ceph
      sourceRef:
        kind: HelmRepository
        name: rook-release
      version: v1.8.6
  install:
    createNamespace: true
  interval: 30m
  releaseName: rook-ceph
  targetNamespace: rook-ceph
  valuesFrom:
  - kind: ConfigMap
    name: rook-ceph-operator-values
