apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: vertical-pod-autoscaler-values
  namespace: flux-system
  files: [values.yaml]
  options: {disableNameSuffixHash: true}
resources:
- helm-release.yaml
- helm-repo.yaml
