apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nitter
configMapGenerator:
- name: redis-values
  files: [redis/values.yaml]
resources:
- ../kustomizeconfig
- redis/helm-release.yaml
- namespace.yaml
