apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nitter
configMapGenerator:
- name: config
  files: [nitter.conf]
  options: {disableNameSuffixHash: true}
- name: nitter-values
  files: [values.yaml]
- name: redis-values
  files: [redis/values.yaml]
resources:
- ../kustomizeconfig
- helm-release.yaml
- namespace.yaml
- redis/helm-release.yaml
