# https://github.com/morremeyer/charts/blob/main/charts/generic/values.yaml

additionalVolumes:
- name: config
  configMap:
    name: config
additionalVolumeMounts:
- name: config
  mountPath: /config
command:
- /bin/ash
- -c
- |-
  set -uexo pipefail
  sed -e "s/__REDISPASS__/$REDIS_PASSWORD/" \
      -e "s/__HMAC__/$HMAC_TOKEN/" \
    < /config/nitter.conf > /nitter.conf
  exec /src/nitter
env:
  NITTER_CONF_FILE: /nitter.conf
envValueFrom:
  REDIS_PASSWORD:
    secretKeyRef:
      name: redis
      key: redis-password
  HMAC_TOKEN:
    secretKeyRef:
      name: hmac
      key: token
image:
  repository: zedeus/nitter
  tag: ecb6fe4162142f7260b36d4ac4021d6ac7cd2b49
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
  className: nginx
  hosts:
  - host: nitter.samcday.com
    paths:
    - path: /
  tls:
  - hosts:
    - nitter.samcday.com
    secretName: certificate
livenessProbe:
  httpGet:
    path: /POTUS
    port: 8080
readinessProbe: ~
replicaCount: 2
service:
  name: nitter
  targetPort: 8080
