apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: secrets
    namespace: juicefs
spec:
    secretTemplates:
        - name: juicefs.juicefs-db.credentials.postgresql.acid.zalan.do
          labels:
            application: spilo
            cluster-name: juicefs-db
            team: juicefs
          stringData:
            username: ENC[AES256_GCM,data:psburzvqMQ==,iv:8C1W2DxuoQUefxtXbiGoqL/zVDDSZgxylRxoBCpBMgQ=,tag:eO1If9/7QmZ3xUU+LEUZnQ==,type:str]
            password: ENC[AES256_GCM,data:D2NbVsQPTh1fVasRiV17nzehLqq4WTesB4IoAlnaPwOuoA9qZO0W2oh7lDJcWQxUXicyrklfdwKBityY2lmizQ==,iv:Ie4AFZMluH/i4+9/MR3fCJzXiWs79bZmgKp1eqEkKMU=,tag:ehHX+xQtFOzfO7QEMWh6dQ==,type:str]
        - name: postgres-pod-secrets
          stringData:
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:lVdjhmr6+Yy2sLaL7Squbf4zVMQPO/mlyg==,iv:DZ7/XWPm9CtaMVh1shfqB0rssQXMec55hUkKNsx9cd4=,tag:DnPY8jgVXjBlSuLizWzbGg==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:wOXYEXELLSuDMpsPeEwliiV9I2B+jvBIdJxhzziBGg==,iv:QvbtWt8evsRIISlJDY0+fL6LS8JH4pu75oENDeNyAHQ=,tag:TVCJDdPRW2TKXjtylyPJ5A==,type:str]
            AWS_ENDPOINT: ENC[AES256_GCM,data:8f2KZRhoXIBHJUsNcEt67zg8F9CqRmy0Or5HRizxWlxmhWk8SujDbbK6K9ZB,iv:j6Vh79c4F61Vvc1yncrwzexWMInSuXP2z5Jyi4TWhrY=,tag:1HGUe27yXhZiRtNgFY2KBw==,type:str]
            WALE_S3_ENDPOINT: ENC[AES256_GCM,data:M5jg5rwgNWrC6qub2NHK+Z9S41KkJwGnQWPkbb5JN/mNGdB4Y2KLgtmhcAJEdbUwrv8=,iv:SRwo+r9COI41B/+rMUOQjytqPioy1Dk5nhwGIXa2fGY=,tag:GFYlYvE+sMlTrtlWVCK8uQ==,type:str]
            CLONE_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:C5edEeNBI6+2wJErODt2e/N+2RFoodKpgA==,iv:9PFxqDjJY6rnmK1HIdR8wdCIGc5KqZjFzYBcv19+qic=,tag:oC/AJuq8wDV06YUMUa5GLQ==,type:str]
            CLONE_AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:6DiaVK8gi0RFBMfnfoCsNmzwTzza3WnlODsF0SmtcA==,iv:W7kofxPVMoWQ2Bs7NjrP5Kv3holWXdUNFzNcSyE05MU=,tag:KiQwtn0YgojsvQiKFHnQaA==,type:str]
            CLONE_AWS_ENDPOINT: ENC[AES256_GCM,data:ieYGLwXQb6JrW3TXK85SjaeMh+G/Rmbn79vDRLOdRGcGwL4wqp2L+JhkAyZi,iv:LRjkoq+RcGqu92pYJVHLnf0BrmOv2sGSj/ToIhAckZw=,tag:g/UJxV+UYei2xw/GusU7tg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kztlwk25hdsy8s2gqlkx4aucdwss5zfaejadtnv5s2zd7vmslq0s8gqltu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtYWxSMytVdEJUWlNKVmxh
            bmJpM3pmQitMNWFDOXZZeVk3N1grUUl3eng0Cm1PSWZ2WFFwV0tZdHB1VW94QTc0
            cjRUYzVaYkc2N1JWaU9SVERCRW1odzAKLS0tIE5HeE4zNUNXZmxNRGNoRTFCL2Za
            dEtMaENaTVAxZXlhaTFQY2g0YW43RVEKrWRowk0puSKqel2xT11DB6q/3mDvkqsC
            JkCwCa3zxaShTCW82yxSz9BaBJNCFEgEEANAC3fR3PP89Ab4TgclXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-08T21:22:37Z"
    mac: ENC[AES256_GCM,data:PDyKwfqcPFkGQJ07BQIz4P1Lw7mv4BGI7+ZrdVpxro/SAt3xXGq9zivZ5Aq/kM4e6yvSstfs5oom5TfQcmTQa4n3Ovaz0xihLA4kc2UGFUtWM9L2bhKMvLuHNZ1MLkXaGBUj+xesdC1irmwDmD1gWPAIox+b8nnj7K660nz9T80=,iv:rc+PMLBCQkipLmKgr8eV8xiATe8NZDtuVFGDbZIjRyA=,tag:t4Lrm5PdCDxmWzwPt1ieUQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
