controller:
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
    limits:
      cpu: "1"
      memory: 256Mi
node:
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
    limits:
      cpu: "1"
      memory: 256Mi
storageClasses:
- name: juicefs-sc
  enabled: true
  reclaimPolicy: Retain
  backend:
    name: juicefs
    storage: s3
    bucket: https://samcday-juicefs.s3.eu-central-003.backblazeb2.com
  mountPod:
    resources:
      limits:
        cpu: 1000m
        memory: 256Mi
