---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
      version: v1.7.1
  install:
    createNamespace: true
  interval: 1h
  releaseName: cert-manager
  targetNamespace: cert-manager
  valuesFrom:
  - kind: ConfigMap
    name: cert-manager-values
