---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: flux-system
spec:
  chart:
    spec:
      chart: promtail
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: 3.9.2
  install:
    createNamespace: true
  interval: 30m0s
  releaseName: promtail
  targetNamespace: monitoring
  values:
    config:
      lokiAddress: http://loki:3100/loki/api/v1/push
    serviceMonitor:
      enabled: true
