---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: flux-system
spec:
  chart:
    spec:
      chart: promtail
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: 3.11.0
  install:
    createNamespace: true
  interval: 30m0s
  releaseName: promtail
  targetNamespace: monitoring
  valuesFrom:
  - kind: ConfigMap
    name: promtail-values
