apiVersion: v1
kind: LimitRange
metadata:
  name: happy-cluster
  namespace: playkube
spec:
  limits:
  - default:
      cpu: 1000m
      memory: 256Mi
    defaultRequest:
      cpu: 10m
      memory: 32Mi
    max:
      cpu: 1000m
      memory: 2Gi
    min:
      cpu: 1m
      memory: 16Mi
    type: Container
